trainer:
  game: "BreakoutDeterministic-v4"
  render_mode: "rgb_array"
  episodes: 10000
  learning_rate: 5e-4
  gamma: 0.95
  n_memory_episodes: 100
  prefix_name: ""
  folder: "logging/BreakoutDeterministic_5e4_stack4_gamma95_per06"
  save_gif_every_x_epochs: 50
  batch_size: 128
  EPS_START: 1
  EPS_END: 0.05
  EPS_DECAY: 250
  TAU: 5e-4
  max_episode_len: 2000
  use_ddqn: true
  replaymemory: 25000
  optimizer: null
  per_alpha: 0.6
  use_scheduler: false
  validate_every_n_episodes: 100
  validate_episodes: 5
  patience: 3
  game_wrapper: null
  visualizer: null
  gif_fps: 20
  update_every_n_steps: 10
  save_diagnostics: 200
  clip_grad: 0
  save_model_every_n: 5
  reset_options:
    randomize_position: false
  warmup_steps: 5000

atari_game_wrapper:
  resize_img: [80, 105]
  gray_scale: true
  random_envs: 0
  default_start_prob: 0.5
  random_steps_range: [10, 100]
  stack_n_frames: 4
  losing_live_penalty: -5