trainer:
  game: "BreakoutNoFrameskip-v4"
  render_mode: "rgb_array"
  episodes: 10000
  learning_rate: 1e-4
  gamma: 0.95
  n_memory_episodes: 250
  prefix_name: ""
  folder: "logging/BreakoutNoFrameskip__llp5_bs256"
  save_gif_every_x_epochs: 250
  batch_size: 256
  EPS_START: 1
  EPS_END: 0.1
  EPS_DECAY: 500
  TAU: 5e-4
  max_episode_len: 2000
  use_ddqn: true
  replaymemory: 25000
  optimizer: null
  per_alpha: 0
  use_scheduler: false
  validate_every_n_episodes: 250
  validate_episodes: 5
  patience: 3
  game_wrapper: null
  visualizer: null
  gif_fps: 20
  update_every_n_steps: 10
  save_diagnostics: 500
  clip_grad: 0
  save_model_every_n: 5
  reset_options:
    randomize_position: false
  warmup_steps: 5000
  value_network_lr: 1e-4 # for A2C only
  actor_network_lr: 1e-4 # for A2C only
  entropy_coefficient: 0.01 # for A2C only
  input_shape: (11, 12, 12) # for A2C only
  epochs: 15000 # for A2C only

atari_game_wrapper:
  resize_img: [80, 105]
  gray_scale: true
  random_envs: 0
  default_start_prob: 0.5
  random_steps_range: [10, 100]
  stack_n_frames: 4
  losing_live_penalty: 1
  normalize_factor: 255
  frame_skip: 4